### ISSUE TITLE
There is no automate marshaling from string to char*

### ISSUE THREAD

**Issue by ciplogic** [ciplogic/CodeRefractor#5]

**Comment by bmustiata** [comment]
Fixed in: https://github.com/ciplogic/CodeRefractor/commit/44b66ab61eb698a4b6527d81f205818d3266b491. Cleaned up in https://github.com/ciplogic/CodeRefractor/commit/4dd2b600b184f32a9ef7847c27741545f626ba79 and  https://github.com/ciplogic/CodeRefractor/commit/b9fd2596ec24b49c8b62673b4e1b3baed852cef7.
